### ISSUE TITLE
Accordion does not work

### ISSUE THREAD

**Issue by clairestreb** [Mallioch/MobileMvcSamples#2]
I think the whole point of an accordion is to be able to open it up, so I added:

```
<li><a href="#">Fourth Link</a>
    <ul>
        <li><a href="#">4.1</a></li>
        <li><a href="#">4.2</a></li>
    </ul>
</li>
```

to AccordionNav.cshtml and FlyoutNav.cshtml, but it doesn't work like an accordion.  Advice?

**Comment by clairestreb** [comment]
I replaced it with http://jqueryui.com/accordion/

**Comment by Mallioch** [comment]
I'm glad you figured out something that will work for you.
